### ISSUE TITLE
Number of entities showing up in HAOS is different across multiple EP Lites

### ISSUE THREAD

**Issue by docwho76** [EverythingSmartHome/everything-presence-lite#125]
Recently recieved my order of 3 EP Lites and started trying to get them setup. Had a bit of a rough time, the documentation isnt always as clear as it could have been. The docs really should emphasize that you need to do the firmware update BEFORE you bother with HAOS stuff at all.

That being said, I have 3 EP Lite setup on 1.07 firmware and latest HAOS and ESPHome versions (see screenshot below).
![2024-07-29 17_51_50-Settings – Home Assistant — Mozilla Firefox](https://github.com/user-attachments/assets/1698886f-f567-48da-8df8-b6082a68c2e5)

The EP Lite only shows 22 entities? And another one shows 21? (The 21 entity one is powered off right now maybe that is why?) Why? I dont get it. Also, its literally in a room with nothing inside that should be triggering the mmWave sensor and it triggers occupant like...every 2-4 seconds! I tried reducing the distance max and min and it didnt seem to help at all. 
[config_entry-esphome-01J3NKS9JE41ES46QEAD4VN6GW.json](https://github.com/user-attachments/files/16420543/config_entry-esphome-01J3NKS9JE41ES46QEAD4VN6GW.json)

![2024-07-29 17_56_05-Settings – Home Assistant — Mozilla Firefox](https://github.com/user-attachments/assets/2e0be8e8-38a4-4024-9726-776fbada25e7)

This is the EP Lite that has what seems to be all of the entities. Its also on 1.0.7 firmware as well. Its presence detection seems to be stable.
![2024-07-29 17_56_39-Settings – Home Assistant — Mozilla Firefox](https://github.com/user-attachments/assets/8a43ddec-feea-4c16-920a-dea4d7d80eaf)

Can I get some guidance on what the heck is going on here?

**Comment by EverythingSmartHome** [comment]
Hello

You don't particularly need to update the firmware before adding it to HA, that's why the docs don't mention it. You can update from Home Assistant after thee fact with no issues.

The reason for the different amount of entities appears to be because you have flash the firmware for the SEN0609 mmWave sensor instead of the LD2450 (which is the default sensor that comes with the device). The documentation page shows pictures and a description of the sensors you can chose, and hides the additional ones by default so you.must have intentionally selected it. 

You can see this because the 2 units with 22 entities on them have controls for "mmWave LED" and "range reduced" as well as other entities, these are not controls that are on the Lite firmware and only present on the one.

This will of course also cause issues with detection when you flash the wrong firmware.

If you go back to the user guide and select the default LD2450 sensor this time then this should resolve the issue.

Let me know how it goes!
