### ISSUE TITLE
High illuminance readings

### ISSUE THREAD

**Issue by V4ler1an** [EverythingSmartHome/everything-presence-lite#148]
One of my EPLs reads very high illuminance, getting up to 500 when according to my other EPLs (which are consistent) it should be more like 10 to 15. Also, the reading varies quite a lot. When I try adjusting the offset, although I can get it closer to where it should be, the reading wanders around too much to be of any real use. Is there anything I can do? Or is this one defective? Here are the versions. Thanks.

![image](https://github.com/user-attachments/assets/a1622ae2-d993-4ae1-934e-55e3f0db3704)
![image](https://github.com/user-attachments/assets/e4612332-c18e-41f0-8118-c4a1895e965f)

**Comment by EverythingSmartHome** [comment]
No, it seems like the devices you have are on different versions. In newer versions of the firmware, there is calibration data added to the light sensor in order to provide better readings when the front cover is on. If you update the other units, you should see similar values - though comparing devices in different rooms is still going to give different readings naturally

**Comment by V4ler1an** [comment]
I haven't got round to the firmware updates on the other yet and looking back, the higher readings started after updating the kitchen. I'll get them done. Thank you.

**Comment by EverythingSmartHome** [comment]
You are welcome!
