### ISSUE TITLE
To Adopt or not Adopt?

### ISSUE THREAD

**Issue by jonlanceley** [EverythingSmartHome/everything-presence-lite#171]
Just after some clarification please as can see in some issues people have adopted in esp home and others who havent.

Whats the best practice to Adopt or dont?

Thankyou

**Comment by EverythingSmartHome** [comment]
If you need/want to make changes to the config then you will need to adopt, but if you don't and you want to use the product as we ship it and get updates from us then no need to. Hope that helps!

**Comment by bcutter** [comment]
@EverythingSmartHome It helps only partly: What exactly will stop to work once the EPL (in my case) gets adopted in ESPHome dashboard?
- Firmware update entity?
- Firmware update via EP Zone Configurator (settings --> firmware updates)?
- ...?
- Will updating the EPL via ESPHome (to e. g. 2026.6.1 at the moment) break any feature?

Overall I still have absolutely no clear idea of what are the consequences of adopting an EPL in ESPHome. Searched the whole docs section and KB articles etc. Could you specifically clarify this please? Thanks a lot!

**Comment by jonlanceley** [comment]
Nothing stops working. Just means you can run the esphome version of your choice e.g. the latest. You still get the epl firmware notifications you then install them from esphome within Home Assistant. You also get esphome firmware notifications.
Running an esphome version ahead of what epl ships with does run the risk of it not compiling but then it wont install to the device anyway. This only happened once that I remember and was fixed quickly

**Comment by bcutter** [comment]
Okay... was just wondering, as ESPHome notices during the adoption attempt that "firmware updates of the vendor won't be applied automatically anymore"...

<img width="821" height="1065" alt="Image" src="https://github.com/user-attachments/assets/87ec9ac0-c3d4-4899-8ffb-ac68194462f9" />

Also, the out of the box update entity signales the Everything Presence Lite firmware version instead of the ESPHome version like I'm used to with ESP devices integrated in HA (currently updating via ESPHome from 2026.5.2 to 2026.6.2), so YES, overall it's rather confusing.

<img width="1007" height="187" alt="Image" src="https://github.com/user-attachments/assets/e8762a83-eeab-496e-bc23-2f80f86f88a4" />

So the firmware update via Everything Presence Zone Configurator app still works, firmware update entity also works, ESP is adopted and can be updated via ESPHome dashboard, BUT **the native "ESP device firmware update" entity is missing**, so I won't recognize available ESPHome updates as I don't check the ESPHome dashboard regularly.

**Comment by bcutter** [comment]
> BUT **the native "ESP device firmware update" entity is missing**, so I won't recognize available ESPHome updates as I don't check the ESPHome dashboard regularly.

I want to come back to this: I discovered over the weeks the ESPHome version is outdated. How about providing a native ESPHome update entity in addition? Disable it by default, allowing users to make their choice. Unfortunately I'm aware of creating update entities manually, but don't know where to get the current at latest available ESPHome version for the Everything Presence device.
