### ISSUE TITLE
No firmware updates available for certain EPLs

### ISSUE THREAD

**Issue by Cyruz143** [EverythingSmartHome/everything-presence-lite#175]
I bought 2x EPLs when they first released with the new cases. HA picked them up and they've all worked flawlessly. I added a 3rd one today, it all went well but I noticed it A) was on a newer version of firmware out of the box and B) it was able to update itself to 1.0.10 (ESPHome 2024.9.1).

The two original ones are stuck on  Firmware: 1.0.3 (ESPHome 2024.5.1). I've tried removing them and re-adding them to HA and I still don't see a way to update the firmware via HA. I don't use any standalone ESPHome bits, just the HA integration. A few images for context below:

![image](https://github.com/user-attachments/assets/877d9441-854b-4f14-9370-47e618a208f2)

New EPL:
![image](https://github.com/user-attachments/assets/a0dd327a-bcbe-425c-9b84-d1c0aabb42d7)
![image](https://github.com/user-attachments/assets/8f7db334-32e4-42ca-a7bf-da66941b7662)

Older EPLs:
![image](https://github.com/user-attachments/assets/51d7a977-6352-4164-83c8-30a824a1e2b6)
![image](https://github.com/user-attachments/assets/808b3a9e-9207-4f1e-83c3-37ac0393a279)

**Comment by EverythingSmartHome** [comment]
Hello,

The "Everything Presence Lite Firmware" option you are seeing was added in a later release. Since you don't use the ESPHome add-on, I would suggest updating your existing units from the user guide here: https://everythingsmarthome.github.io/everything-presence-lite/updating.html#manual-setup-and-factory-resetting

You will need to do this over USB first, but after updated then future updates can be done wirelessly.

**Comment by Cyruz143** [comment]
All done and super easy, shame Firefox isn't supported for web flashing but really neat process regardless.

Thanks!
