### ISSUE TITLE
No detection if staying still?

### ISSUE THREAD

**Issue by guilhermednt** [EverythingSmartHome/everything-presence-lite#43]
Is it normal for the Everything Presence Lite to stop detecting presence if I'm staying still?

I had the impression that the mmWave sensor's goal was to be able to detect the slightest of movements like breathing, however when I'm in bed it often stops detecting me.

The sensor is positioned ~3.1m away from me, with line of sight and the max. distance is set to 4m.

Below is an image showing what a night of sleep looks like.
I was expecting it to detect occupancy for the whole timeframe, however most of the time it's reporting no occupancy.

![image](https://github.com/EverythingSmartHome/everything-presence-lite/assets/860796/57e09fbf-7590-4dc8-9016-8fc5f282f69c)

Just trying to figure out if this is the expected behavior, if I did something wrong or even got a defective unit.

**Comment by EverythingSmartHome** [comment]
Hello!

mmWave does detect very fine movement yes (as evidence by it catching you sometimes when sleeping) but it depends on a few factors such as distance to sensor and positioning - also some sensors are more optimised for certain functions, the LD2450 that comes with the Lite for example favours doing Zones more than purely static presence. The mmWave sensor in the EP1 is better at static detection with adjustable sensitivity. But that's why we made the Lite with switchable sensors so you can pick the best sensor for your environment.

That said, there is also the misconception that the max range of a device means that it can detect the smallest movement at that max range which isn't always true.

Anyways, just a bit of background!

As for practical solutions, one thing you could try to do is increasing the occupancy off delay to account for these periods, another thing you can do is move it closer, or you could even try it under the bed facing directly up, I've had good results with that before (though on a different sensor)

**Comment by guilhermednt** [comment]
Thanks for the quick reply!

My biggest concern was if there was something wrong, but if that's about what is expected then I'll just adjust the positioning.
